board: MKS-DLC32 V2.1
name: qtdraw 5
meta: villamany 30/Jan/2023

kinematics:
  Cartesian:

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: I2SO.0
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 500
    max_travel_mm: 200
    soft_limits: true
    homing:
      cycle: 2
      #allow_single_axis: false
      positive_direction: false
      feed_mm_per_min: 500.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.000
      feed_scaler: 1.000

    motor0:
      hard_limits: true
      pulloff_mm: 5
      limit_all_pin: gpio.36:high
      stepstick:
        step_pin: I2SO.1
        direction_pin: I2SO.2:high

  y:
    steps_per_mm: 80
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 500
    max_travel_mm: 240
    soft_limits: true
    #pulloff_mm: 2.000
    homing:
      cycle: 3
      #allow_single_axis: false
      positive_direction: false
      feed_mm_per_min: 500.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.000
      feed_scaler: 1.000

    motor0:
      hard_limits: true
      limit_all_pin: gpio.35:high
      pulloff_mm: 5
      stepstick:
        step_pin: I2SO.5
        direction_pin: I2SO.6:low
 
  z:
    steps_per_mm: 1600
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 120
    max_travel_mm: 31
    soft_limits: true
    homing:
      cycle: 1
      mpos_mm: 25.1
      #allow_single_axis: true
      positive_direction: true
      feed_mm_per_min: 250.000
      seek_mm_per_min: 500.000
      settle_ms: 500
      seek_scaler: 1.000
      feed_scaler: 1.000

    motor0:
      hard_limits: true
      limit_pos_pin: gpio.34
      pulloff_mm: 5
      stepstick:
        step_pin: I2SO.3
        direction_pin: I2SO.4:low
 
i2so:
  bck_pin: gpio.16
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.12
  mosi_pin: gpio.13
  sck_pin: gpio.14

sdcard:
  cs_pin: gpio.15
  card_detect_pin: gpio.39
  
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

macros:
  startup_line0:
  startup_line1:
  macro0:
  macro1:
  macro2:
  macro3:

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

  
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

probe:
  pin: gpio.22:low
  check_mode_start: true

start:
  must_home: true
